### ISSUE TITLE
Optionally disable genome and/or phenotype clustering

### ISSUE THREAD

**Issue by abremges** [aweimann/traitar#47]
In some cases, it might be desired to disable the clustering. Instead, sort the genome rows by input order, and/or the phenotype columns by some intrinsic order (that makes sense, i.e. pre-clustered by type or simply alphabetically?).

**Comment by abremges** [comment]
Dendrogram(s) should be disabled in these cases, obviously.

**Comment by aweimann** [comment]
That would indeed be a nice feature. Implementation should be straight forward. I think it makes sense both for samples and phenotypes. For samples one could just take the input order. For phenotypes one could sort by the category so that e.g. carbohydrate-related phenotypes stay together.

**Comment by abremges** [comment]
Exactly! :+1:

**Comment by aweimann** [comment]
This is now implemented in the most recent version of Traitar.

**Comment by abremges** [comment]
Awesome, thanks!
