### ISSUE TITLE
Packaging of config file

### ISSUE THREAD

**Issue by abremges** [aweimann/traitar#49]
Taken from #48:

> Unfortunately my own config file was packaged into the Traitar source distribution, which is why it's looking for the aaron folder.

Is this something you can easily change in future releases?
We should ship a vanilla version of the Traitar software.

From my understanding, the config file gets created during/after the initial installation?
Then it shouldn't be a problem for new users, but _maybe_ for users who update Traitar...

**Comment by aweimann** [comment]
Absolutely, the specific behaviour is because the config file got accidentally packaged into the source distribution and replaced the user config. You're right that I need to check if in general upon update the user config file get deleted.

Thanks, Aaron
