### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by suzumar** [aweimann/traitar#52]
Hello. I have installed traitar in a mac, and runs OK, except I get this error message during heatmap generation

traitar phenotype /work/01_SAG/05_traitar/01_input /work/01_SAG/05_traitar/Traitar_samples.txt from_nucleotides /work/01_SAG/05_traitar/02_output -c 4

/usr/local/sources/bioinfo/lib/python2.7/site-packages/matplotlib/axes/_base.py:3045: UserWarning: Attempting to set identical bottom==top results
in singular transformations; automatically expanding.
bottom=0, top=0.0
  'bottom=%s, top=%s') % (bottom, top))
Traceback (most recent call last):
  File "/usr/local/sources/bioinfo/bin/heatmap.py", line 482, in <module>
    heatmap(matrix, row_header, column_header, primary_pt_models, args.color_f, args.row_method, args.column_method, args.row_metric, args.column_metric,   args.out_f, args.sample_f, secondary_pt_models)
  File "/usr/local/sources/bioinfo/bin/heatmap.py", line 278, in heatmap
    dr = dr[idx1]
UnboundLocalError: local variable 'idx1' referenced before assignment
/usr/local/sources/bioinfo/lib/python2.7/site-packages/matplotlib/axes/_base.py:3045: UserWarning: Attempting to set identical bottom==top results
in singular transformations; automatically expanding.
bottom=0, top=0.0
  'bottom=%s, top=%s') % (bottom, top))
Traceback (most recent call last):
  File "/usr/local/sources/bioinfo/bin/heatmap.py", line 482, in <module>
    heatmap(matrix, row_header, column_header, primary_pt_models, args.color_f, args.row_method, args.column_method, args.row_metric, args.column_metric,   args.out_f, args.sample_f, secondary_pt_models)
  File "/usr/local/sources/bioinfo/bin/heatmap.py", line 278, in heatmap
    dr = dr[idx1]
UnboundLocalError: local variable 'idx1' referenced before assignment
/usr/local/sources/bioinfo/lib/python2.7/site-packages/matplotlib/axes/_base.py:3045: UserWarning: Attempting to set identical bottom==top results
in singular transformations; automatically expanding.
bottom=0, top=0.0
  'bottom=%s, top=%s') % (bottom, top))
Traceback (most recent call last):
  File "/usr/local/sources/bioinfo/bin/heatmap.py", line 482, in <module>
    heatmap(matrix, row_header, column_header, primary_pt_models, args.color_f, args.row_method, args.column_method, args.row_metric, args.column_metric,   args.out_f, args.sample_f, secondary_pt_models)
  File "/usr/local/sources/bioinfo/bin/heatmap.py", line 278, in heatmap
    dr = dr[idx1]
UnboundLocalError: local variable 'idx1' referenced before assignment

**Comment by aweimann** [comment]
Hi, thanks for your interest in Traitar! It's great to hear that it runs in a mac as well. 
You have spotted a bug in the heatmap plotting. I've fixed it now and put a new release on pypi: 1.1.2 Can you try if it works for you? 

Cheers, Aaron

**Comment by suzumar** [comment]
No problems.  Thanks a lot for the very quick answer :)

	Marcelino
============================================================================
            oOOOOo                 		 Professor Marcelino Suzuki,  Director 
          oOOO     Sorbonne Universités (UPMC)  - CNRS Inst Ecologie et Environnement (InEE)
       oOOOOOo.       USR 3579 LBBM - Laboratoire de Biodiversité et Biotechnologies Microbiennes 
    .oOOOOOOOo.                         Observatoire Oceanologique de Banyuls-sur-Mer
  .oOOOOOOOOOoo.      Ave Pierre Fabre, Banyuls-sur-Mer 66650, France  +33(0)430192401 
.oOOOOOOOOOOOooooo.   	 suzuki@obs-banyuls.fr http://bit.ly/1pxPvl3
00000000000000000000000000000000000000000000000000000000000000000000000000000000

**Comment by abremges** [comment]
I've tested v1.1.2 on my Macbook and it ran smoothly, therefore I assume it also worked for you.
@suzumar, please simply post here (or open a new issue) if the issue wasn't resolved – thanks!

**Comment by suzumar** [comment]
I did not have time to install run it, and will let you know ASAP

	Thanks
	
Marcelino
============================================================================
            oOOOOo                 		 Professor Marcelino Suzuki,  Director 
          oOOO     Sorbonne Universités (UPMC)  - CNRS Inst Ecologie et Environnement (InEE)
       oOOOOOo.       USR 3579 LBBM - Laboratoire de Biodiversité et Biotechnologies Microbiennes 
    .oOOOOOOOo.                         Observatoire Oceanologique de Banyuls-sur-Mer
  .oOOOOOOOOOoo.      Ave Pierre Fabre, Banyuls-sur-Mer 66650, France  +33(0)430192401 
.oOOOOOOOOOOOooooo.   	 suzuki@obs-banyuls.fr http://bit.ly/1pxPvl3
00000000000000000000000000000000000000000000000000000000000000000000000000000000
