### ISSUE TITLE
Doesnt work for me at the first step

### ISSUE THREAD

**Issue by fauziharoon** [aweimann/traitar#53]
lala@kw1322:~/projects/traitar_results$ traitar phenotype ../IMG_annotation/ samples.txt from_genes .
Traceback (most recent call last):
  File "/usr/local/bin/traitar", line 492, in <module>
    args.func(args)
  File "/usr/local/bin/traitar", line 32, in phenolyze
    p = Traitar(args.input_dir, args.output_dir, args.sample2file, args.cpus, args.rearrange_heatmap, args.heatmap_format, args.no_heatmap_phenotype_clustering, args.no_heatmap_sample_clustering, args.gene_gff_type, args.primary_models, args.secondary_models)
  File "/usr/local/bin/traitar", line 71, in __init__
    self.s2f = self.parse_sample_f()
  File "/usr/local/bin/traitar", line 142, in parse_sample_f
    if len(i) > 30:
TypeError: object of type 'float' has no len()

**Comment by aweimann** [comment]
Hi, thanks for reporting your problem. I have to take a closer look still but it might be that your samples have numeric names and  get automatically converted to floats, when reading the sample file. For a quick fix you could try adding some prefix. I can dig deeper tomorrow. 

Cheers, Aaron

**Comment by aweimann** [comment]
Hi Fauzi,

I'm very sorry for letting you wait so long. I tried a few things but I couldn't really reproduce your problem. Could you send me / post here your sample file you use as input to Traitar. 

Cheers, Aaron

**Comment by fauziharoon** [comment]
Hi Aaron,

It is working now. 

Just getting this when i run traitar phenotype:
`
running annotation with hmmer. This step can take a while. A rough estimate for sequential Pfam annotation of genome samples of ~3 Mbs is 10 min per genome.
Unknown option: will-cite
Unknown option: will-cite
`

**Comment by abremges** [comment]
Thank you, @fauziharoon. This is merely a "cosmetic" annoyance (see https://github.com/aweimann/traitar/issues/51, which I leave open), but it does not interfere with Traitar's functionality. Glad Traitar is working for you now!

**Comment by lanlan0210** [comment]
Hello, I have the same problem. 

TypeError: object of type 'float' has no len()

How did you solve it? Can you tell me about it? Thank you very much.
