### ISSUE TITLE
Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by swuyts** [aweimann/traitar#55]
Hi there,

Just read about traitar and wanted to give it a shot! Installation went fine, however it looks like I'm not able to make it run. After calling traitar I get the following error:

`  File "/usr/local/bin/traitar", line 173
    print  self.user_message % out_dir
              ^
SyntaxError: Missing parentheses in call to 'print'
`

I've played a little bit around with this error by commenting out this print line, but then another line pops up. If I'm correct, this seems like an error related to using the Python2 print vs. the Python3 print function.

traitar installed as a python3.4 module using pip. Should I install using pip2 instead?

Thanks, looking forward to use traitar!

Sander

**Comment by swuyts** [comment]
I was maybe a little bit to early posting this:

`pip2 install traitar-<version>.tar.gz --user`

worked perfectly.

**Comment by aweimann** [comment]
Hi Sander, 

thanks for your interest in our software! Traitar was implemented in Python 2.7 We might port it to Python 3 in the future, but I'm glad to hear that you could get it installed with pip2. Please let me know if you run into further problems. I'm also always happy about any useful comments or suggestions. 

Many thanks,

Aaron

**Comment by swuyts** [comment]
Thanks for the clarification Aaron,

It's running smoothly now, so I'm very much looking forward to the results!

Since I'm here, one small suggestion to smoothen the installation procedure
for others may be placing a link to the latest tar.gz on the installation
page. It took me a while to find one trough the python package website.

Regards,
Sander

**Comment by aweimann** [comment]
Thanks for the suggestion! You can also install traitar without specifying a tar.gz i.e. pip install --user traitar. The latest tar.gz can be found on the release site: https://github.com/hzi-bifo/traitar/releases . I will add both hints to the installation description.

Cheers, Aaron
