### ISSUE TITLE
SyntaxError: Missing parentheses in call to 'print'.

### ISSUE THREAD

**Issue by jahicks4** [aweimann/traitar#66]
I installed this using pip, the required python packages as well as Prodigal and hmmsearch are also installed, but when I try to run it, I get the following error:

  File "/usr/local/bin/anaconda3/bin/traitar", line 173  
    print  self.user_message % out_dir  
              ^             
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(print  self.user_message % out_dir)?

It looks like it didn't install the most recent updates that can be seen here, so maybe the code is fixed, but pip isn't getting the latest updates???

**Comment by aweimann** [comment]
Thanks for your interest. Traitar is still a Python 2 package. So you have to make sure you are installing it into a Python 2.7 environment https://conda.io/docs/user-guide/tasks/manage-python.html . 

Cheers, Aaron

**Comment by jahicks4** [comment]
Thanks for the reply- I didn’t realize it was in 2.7.  Are there any plans for it to be upgraded to the current version of Python?

Thanks,
Jess

--
Jessica Hicks
Computational Biologist
USDA APHIS VS
National Veterinary Services Laboratories
1920 Dayton Avenue  Ames, IA 50010
515-450-6935

**Comment by aweimann** [comment]
I am sorry but at the moment there are no imminent plans to upgrade to Python 3.
